# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - tech-lead
  - senior-developer
  - security-reviewer

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers
numberOfReviewers: 2

# A list of assignees, overrides reviewers if set
assignees:
  - project-manager

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
numberOfAssignees: 0

# A list of keywords to be skipped the process if PR's title include it
skipKeywords:
  - wip
  - draft
