global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'pagerduty-critical'
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        title_link: 'https://grafana.headai.com/alerts'
        footer: 'Head AI Monitoring'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'https://grafana.headai.com/alerts'

  - name: 'pagerduty-critical'
    pagerduty_configs:
      - service_key: YOUR_PAGERDUTY_SERVICE_KEY
        send_resolved: true
        description: '{{ template "pagerduty.description" . }}'
        client: 'Head AI Monitoring'
        client_url: 'https://grafana.headai.com'
        severity: critical

templates:
  - '/etc/alertmanager/templates/*.tmpl'
