environment: production
debug: false
log_level: WARNING

# Database Configuration
database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: head_ai_prod
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  ssl_mode: require
  connection_pool: 20
  max_connections: 100

# API Configuration
api:
  host: 0.0.0.0
  port: 8000
  base_url: https://api.headai.com
  enable_docs: false
  cors_origins: ["https://headai.com"]

# Monitoring Configuration
monitoring:
  system_check_interval: 30
  error_tracking: true
  performance_monitoring: true
  log_retention_days: 90
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 85
    error_rate: 5

# Feature Flags
features:
  experimental: false
  beta_features: false
  debug_tools: false

# Security
security:
  jwt_expiry: 6h
  refresh_token_expiry: 7d
  password_reset_expiry: 30m
  rate_limit:
    enabled: true
    requests_per_minute: 30
  ssl:
    enabled: true
    cert_path: ${SSL_CERT_PATH}
    key_path: ${SSL_KEY_PATH}

# Cache Configuration
cache:
  type: redis_cluster
  nodes: ${REDIS_NODES}
  password: ${REDIS_PASSWORD}
  max_size: 20GB
  ttl: 4h
  backup: true

# Storage
storage:
  type: s3
  bucket: head-ai-production
  region: us-east-1
  backup:
    enabled: true
    interval: 6h
    retention_days: 30
    multi_region: true

# Notifications
notifications:
  email:
    enabled: true
    smtp_host: ${SMTP_HOST}
    smtp_port: ${SMTP_PORT}
    smtp_user: ${SMTP_USER}
    smtp_password: ${SMTP_PASSWORD}
    from_email: support@headai.com
  slack:
    enabled: true
    webhook_url: ${SLACK_WEBHOOK_URL}
    alert_channel: "#prod-alerts"

# Analytics
analytics:
  enabled: true
  tracking_id: ${ANALYTICS_ID}
  anonymize_ip: true
  sampling_rate: 100

# AI Models
ai_models:
  default_model: gpt-4
  temperature: 0.7
  max_tokens: 4000
  cache_responses: true
  fallback_models:
    - gpt-3.5-turbo
    - gpt-4-base

# Error Reporting
error_reporting:
  sentry_dsn: ${SENTRY_DSN}
  environment: production
  traces_sample_rate: 0.1
  
# Performance
performance:
  auto_scaling:
    enabled: true
    min_instances: 3
    max_instances: 10
    target_cpu_utilization: 70
  cdn:
    enabled: true
    provider: cloudflare
  load_balancing:
    enabled: true
    algorithm: round_robin
