### Bandit config file generated for HeadAI

# Skip test cases
skips:
  # Skip assert statements in test files
  - B101:assert_used:tests/

# Set the output format
format: json

# Specify the confidence level
confidence-level: HIGH

# Specify the severity level
severity-level: LOW

# Configure individual tests
any_other_function_with_shell_equals_true:
  no_shell: true

hardcoded_tmp_directory:
  tmp_dirs:
    - /tmp
    - /var/tmp
    - /dev/shm

linux_commands_wildcard_injection:
  no_shell: true

password_config:
  # Identify potential password strings
  function_names:
    - password
    - passwd
    - pwd
    - secret
    - token
    - api_key

ssl_with_bad_defaults:
  bad_protocol_versions:
    - PROTOCOL_SSLv2
    - SSLv2_METHOD
    - SSLv23_METHOD
    - PROTOCOL_SSLv3
    - PROTOCOL_TLSv1
    - SSLv3_METHOD
    - TLSv1_METHOD

shell_injection:
  subprocess_popen_with_shell_equals_true:
    no_shell: true
  subprocess_without_shell_equals_true:
    no_shell: true

start_process_with_partial_path:
  subprocess_popen_with_shell_equals_true:
    no_shell: true

subprocess_popen_with_shell_equals_true:
  no_shell: true

try_except_pass:
  check_typed_exception: true

# Blacklist various calls
blacklist_calls:
  bad_name_sets:
    - pickle:
        qualnames:
          - pickle.loads
          - pickle.load
          - pickle.Unpickler
    - subprocess:
        qualnames:
          - subprocess.Popen
          - subprocess.call
          - subprocess.check_call
          - subprocess.check_output
          - subprocess.run
    - yaml:
        qualnames:
          - yaml.load
          - yaml.load_all

blacklist_imports:
  bad_import_sets:
    - telnetlib:
        imports:
          - telnetlib
    - ftplib:
        imports:
          - ftplib

# Configure profiles
profiles:
  # High severity issues
  high_severity:
    include:
      - B602  # subprocess_popen_with_shell_equals_true
      - B605  # start_process_with_partial_path
      - B611  # django_rawsql_used
      - B703  # django_mark_safe
      - B308  # mark_safe
      - B501  # request_with_no_cert_validation
      - B503  # ssl_with_bad_version
      - B504  # ssl_with_no_version
      - B505  # weak_cryptographic_key
      - B506  # yaml_load
      - B507  # ssh_no_host_key_verification
      - B601  # paramiko_calls
      - B602  # subprocess_popen_with_shell_equals_true
      - B603  # subprocess_without_shell_equals_true
      - B604  # any_other_function_with_shell_equals_true
      - B608  # hardcoded_sql_expressions
      - B609  # linux_commands_wildcard_injection

  # Medium severity issues
  medium_severity:
    include:
      - B101  # assert_used
      - B102  # exec_used
      - B103  # set_bad_file_permissions
      - B104  # hardcoded_bind_all_interfaces
      - B105  # hardcoded_password_string
      - B106  # hardcoded_password_funcarg
      - B107  # hardcoded_password_default
      - B108  # hardcoded_tmp_directory
      - B110  # try_except_pass
      - B112  # try_except_continue

  # Low severity issues
  low_severity:
    include:
      - B201  # flask_debug_true
      - B301  # pickle
      - B302  # marshal
      - B303  # md5
      - B304  # ciphers
      - B305  # cipher_modes
      - B306  # mktemp_q
      - B307  # eval
      - B401  # import_telnetlib
      - B402  # import_ftplib
      - B403  # import_pickle
      - B404  # import_subprocess
      - B405  # import_xml_etree
      - B406  # import_xml_sax
      - B407  # import_xml_expat
      - B408  # import_xml_minidom
      - B409  # import_xml_pulldom
      - B410  # import_lxml
      - B411  # import_xmlrpclib
      - B412  # import_httplib
      - B413  # import_urllib_urlopen
